#!/bin/bash
#
#SBATCH -J test_gtx1080
#SBATCH -N 1
#SBATCH --partition gpu_gtx1080single
#SBATCH --qos gpu_gtx1080single
#SBATCH --gres gpu:1

# uncomment to receive a notification
####SBATCH --mail-type=BEGIN
####SBATCH --mail-user=youremail

module purge
module load cuda/10.0.130

echo "CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES
echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST="$SLURM_JOB_NODELIST
echo "SLURM_NNODES="$SLURM_NNODES
echo "SLURM_JOB_NAME"$SLURM_JOB_NAME
echo "SLURM_SUBMIT_DIR="$SLURM_SUBMIT_DIR

./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights -ext_output data/person.jpg
